### ISSUE TITLE
Education

### ISSUE THREAD

**Issue by ethyl2** [ethyl2/worry-dolls#7]
I think it would very informative to have a section or page that goes into greater detail about the history and use of worry dolls.

**Comment by Such6** [comment]
Can you assign this to me

**Comment by ethyl2** [comment]
@Such6, yes, thank you!

**Comment by Such6** [comment]
Can you check the updates

**Comment by ethyl2** [comment]
Thanks for your PR! Please see my comment about one update.

**Comment by Such6** [comment]
Can you review the updates! I have created a new branch called updates

**Comment by Such6** [comment]
can you close it

**Comment by Such6** [comment]
Can you tag this issue as hacktoberfest also
